#!/bin/bash -l
#SBATCH -J Si
#SBATCH -p development
#SBATCH -t 00:20:00
#SBATCH --nodes=1
#SBATCH -n 64
#SBATCH -c 4
#SBATCH --output=test_mpi-out.%j
#SBATCH --error=test_mpi-err.%j
#SBATCH --mail-user=guy.ohad@weizmann.ac.il
#SBATCH --mail-type=end
#SBATCH --core-spec=2

export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

MPIRUN='ibrun'
EXE='/home1/07352/tg866516/apps/quantum_espresso/qe_6.2_wannier_constr_dat/q-e_private/bin/pw.x'
PWFLAGS='-nb 4'

$MPIRUN $EXE $PWFLAGS -input si.in &> si.out
